type Disc @model {
  id: ID!
  name: String
  manufacturer: String
  discType: String
  plastic: String
  weight: String
  color: String
  condition: String
  flight: String
  notes: String
  addedAt: String
}
